### ISSUE TITLE
test_node always reports as server not found 

### ISSUE THREAD

**Issue by vishalud** [chadillac/ejabberd-easy_cluster#4]
(ejabberd@ip-172-30-0-115)2> easy_cluster:test_node('ejabberd@172-30-1-221').
server could NOT be reached.
ok

I've confirmed that beam is listening on the private interfaces on both my nodes 

ubuntu@ip-172-30-0-115:~$ sudo   netstat -pant | grep beam | grep LISTEN
tcp        0      0 0.0.0.0:5269            0.0.0.0:*               LISTEN      3777/beam       
tcp        0      0 0.0.0.0:5280            0.0.0.0:*               LISTEN      3777/beam       
tcp        0      0 0.0.0.0:4000            0.0.0.0:*               LISTEN      3777/beam       
tcp        0      0 172.30.0.115:7777       0.0.0.0:*               LISTEN      3777/beam       
tcp        0      0 0.0.0.0:5222            0.0.0.0:*               LISTEN      3777/beam       
tcp        0      0 0.0.0.0:5223            0.0.0.0:*               LISTEN      3777/beam       

ubuntu@ip-172-30-1-221:/usr/lib/ejabberd/ebin$ sudo   netstat -pant | grep beam | grep LISTEN
tcp        0      0 0.0.0.0:5269            0.0.0.0:*               LISTEN      2454/beam       
tcp        0      0 0.0.0.0:5280            0.0.0.0:*               LISTEN      2454/beam       
tcp        0      0 0.0.0.0:4000            0.0.0.0:*               LISTEN      2454/beam       
tcp        0      0 172.30.1.221:7777       0.0.0.0:*               LISTEN      2454/beam       
tcp        0      0 0.0.0.0:5222            0.0.0.0:*               LISTEN      2454/beam       
tcp        0      0 0.0.0.0:5223            0.0.0.0:*               LISTEN      2454/beam   

Any idea why this would be happening ??

**Comment by chadillac** [comment]
Read over my previous configuration guides from my blog. You'll need to make sure the host names are correct in you conf, the ips are correct, and the erlang identification cookie is identical on both machines.  Only once all of these configuration pieces are in place and the services have been restarted will the other features work.

**Comment by vishalud** [comment]
Everything seems to be the same. Test_node gives me a server is up but
joining a cluster does not do anything

**Comment by chadillac** [comment]
Test Node tells you the server is unreachable.

**Comment by ankitsheth111** [comment]
You also need to enter your ejabberd@HOST in /etc/hosts file, both at master (only master host and child - both master and child hosts) and child machines
