### ISSUE TITLE
can easy_cluster can have more than two master?

### ISSUE THREAD

**Issue by indie21** [chadillac/ejabberd-easy_cluster#5]
sync_node(NodeName) ->
        [{Tb, mnesia:add_table_copy(Tb, node(), Type)} 
        || {Tb, [{NodeName, Type}]} <- [{T, mnesia:table_info(T, where_to_commit)}
        || T <- mnesia:system_info(tables)]].

this code don't copy the NodeName's table to it's local, due to   " {Tb, [{NodeName, Type}]} <- [{T, mnesia:table_info(T, where_to_commit)} "  will not match any table  after you have two master, there will be no table to be mnesia:add_table_copy .

am i right ?

if i don't ,
the third master don't have the table copy ， how can it be a real master ... the other two maste crash will make all the table crash.

**Comment by chadillac** [comment]
This tool and technique was pulled together from a handful of other resources I found online, and at this point this project is 3 years old.  I haven't touched it and am not in the right mental space to honestly answer this honestly without digging back into the land of Erlang, Mnesia, and Ejabberd.

That said, this functionality was written for the explicit purpose of stopping the reliance on a single master server from bringing a cluster to a deadlock.  In my testing I spun up multiple servers in a 4 node cluster and cycled them all.  This means that servers srv1, srv2, srv3, srv4 were all joined as masters, with all other nodes being killed and re-added to a running network WHILE clients were programmed to generate messages with incremental payloads (msg 1, msg 2, ... msg 10000) to ensure delivery and stability.

These nodes existed behind a load-balancer and were also accessible via direct naming (srvs == LB, srv1 == srv1, etc.) and the clients had disconnection and re-connection logic.  In these tests 2 clients connected and were joined to whichever server the load-balancer assigned to them in some cases, and in other cases they were locked to a specific instance by name.

The cluster would be brought up with multiple all boxes joined as masters, I believe I tested multiple configurations of this as well where all secondary masters joined of a single master, and another test where all masters joined off of a mastered peer.

srv1
 |- srv2
 |- srv3
 |- srv4

srv1
  |- srv2
        |- srv3
              |- srv4

Then the clients would connect and begin the automated exchange of messages.  As this happened servers would be removed from the cluster until only a single server remained, and then the other boxes would rejoin as masters.  This process was done for every server to ensure functionality and routing would not break given server outages.  All of these tests worked as expected, if not this plugin/feature would have never been released publicly for others to use/experiment with.

Sorry I can't technically answer your question, and I suggest you do some testing with a 3+ node cluster to confirm/deny my claims for yourself.
